<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>FarmExchange</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' != 'Debug' And '$(Configuration)' != 'ExportDebug'">
    <Compile Remove="scripts/**/development/**/*.cs" />
    <Compile Remove="tests/**/*.cs" />
  </ItemGroup>
</Project>
